// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Data$AuthorsAndPosts = require("./Data.bs.js");

var resolvers = {
  posts: (function (author) {
      return Data$AuthorsAndPosts.posts.filter((function (post) {
                    return +(post.authorId === author.id);
                  }));
    })
};

var typeDef = "\n  type Author {\n    id: Int!\n    firstName: String\n    lastName: String\n    posts: [Post] # the list of Posts by this author\n  }\n";

exports.typeDef   = typeDef;
exports.resolvers = resolvers;
/* No side effect */
