// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';


var authors = /* array */[
  {
    id: 1,
    firstName: "Tom",
    lastName: "Coleman"
  },
  {
    id: 2,
    firstName: "Sashko",
    lastName: "Stubailo"
  },
  {
    id: 3,
    firstName: "Mikhail",
    lastName: "Novikov"
  }
];

var posts = /* array */[
  {
    id: 1,
    authorId: 1,
    title: "Introduction to GraphQL",
    votes: [2]
  },
  {
    id: 2,
    authorId: 2,
    title: "Welcome to Apollo",
    votes: [3]
  },
  {
    id: 3,
    authorId: 2,
    title: "Advanced GraphQL",
    votes: [1]
  },
  {
    id: 4,
    authorId: 3,
    title: "Launchpad is Cool",
    votes: [7]
  }
];

exports.authors = authors;
exports.posts   = posts;
/* No side effect */
