// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
"use strict";

var Pervasives = require("bs-platform/lib/js/pervasives.js");
var Caml_exceptions = require("bs-platform/lib/js/caml_exceptions.js");
var Data$AuthorsAndPosts = require("./Data.bs.js");

var MissingPost = Caml_exceptions.create(
  "Mutation-AuthorsAndPosts.MissingPost"
);

var resolvers = {
  upvotePost: function(_, filter) {
    var match = Data$AuthorsAndPosts.posts.find(function(post) {
      return +(post.id === filter.postId);
    });
    if (match !== undefined) {
      match.votes[0] = (match.votes[0] + 1) | 0;
      return match;
    } else {
      throw [
        MissingPost,
        "Couldn't find post with id " + Pervasives.string_of_int(filter.postId),
      ];
    }
  },
};

var typeDef = "\n  type Mutation {\n    upvotePost(postId: Int!): Post\n  }\n";

exports.typeDef = typeDef;
exports.MissingPost = MissingPost;
exports.resolvers = resolvers;
/* No side effect */
