// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Data$AuthorsAndPosts = require("./Data.bs.js");

var resolvers = {
  posts: (function () {
      return Data$AuthorsAndPosts.posts;
    }),
  author: (function (_, filter) {
      var match = Data$AuthorsAndPosts.authors.find((function (author) {
              return +(author.id === filter.id);
            }));
      if (match !== undefined) {
        return match;
      } else {
        return undefined;
      }
    })
};

var typeDef = "\n  type Query {\n    posts: [Post]\n    author(id: Int!): Author\n  }\n";

exports.typeDef   = typeDef;
exports.resolvers = resolvers;
/* No side effect */
